### ISSUE TITLE
Selecting an empty tone data, then selecting another one and trying to play it results in tone data not being played

### ISSUE THREAD

**Issue by josephsl** [nvdaaddons/toneMaster#1] opened 2016-07-19 21:15 UTC
Hi,

It might be just my computer: when you create an empty tone data, select it, play it, select another and play that one, tone data will not be played.

STR:

1. With add-on 1.1 installed, create an empty tone data.
2. Select the newly created empty tone data.
3. Play it.
4. Select another tone data where data is defined.
5. Play the second one.

Expected: NVDA plays the newly selected tone data (not the empty one).
Actual: no playback.

Setup:

* NVDA version: next.13436.
* Windows version: Windows 10 Version 1511.
* Add-on version: 1.1.

Thanks.

**Comment by hkatic** [comment] 2016-07-19 22:09
I reproduced the issue. Yes it's definitely a bug that I haven't noticed before. The workaround is to stop playback and then replay the tone data. The problem is: TM doesn't detect that file is empty, so it'll not reset the playing variable back to False accordingly. This'll be easy to address.

**Comment by hkatic** [comment] 2016-07-20 09:20
Fixed in latest commit: https://github.com/nvdaaddons/toneMaster/commit/764726f495e3543a507016904ac0cb3992ffa7d5

**Closed by hkatic** 2016-07-20 09:20 UTC
